### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by einsqing** [Fictionarry/TalkingGaussian#14]
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by wRinnori** [comment]
i have a same problem，have you solved it?

**Comment by einsqing** [comment]
> i have a same problem，have you solved it?

Not solved

**Comment by wRinnori** [comment]
i have solved it.Just run the command:
`unset LD_LIBRARY_PATH`
After that, the problem should be solved. If you have a another problem like this:
`Not compiled with GPU support`
it seems that your pytorch3d have no GPU support

**Comment by wRinnori** [comment]
I am sorry.It seems that not a good solution，because it may cause some other problem

**Comment by Fictionarry** [comment]
Ensure pytorch and cudatoolkit version in the conda environment match that of your local cuda.

**Comment by wRinnori** [comment]
Thank you so much! The CUDA version I had previously was 11.3.0. After updating it to 11.3.1, this issue was resolved.

**Comment by Coooderr** [comment]
Using cuda/11.3 pytorch/1.12.1 python/3.10 (same as ER-NeRF) can work.
